INSERT INTO haikus (line1, line2, line3, author, emoji) VALUES

    ('It''s enviable.', 'The gracefulness of', 'The cat''s love.', 'Ochi Etsujin', 'cat'),
    ('Only Mount Fuji', 'Is left unburied', 'By young leaves.', 'Yosa Buson', 'fuji'),
    ('The canola flowers.', 'The moon in the east.', 'The sun in the west.', 'Yosa Buson', 'moon'),
    ('I curse the man', 'Who is the man loved by me.', 'A cotten rose.', 'Hasegawa Kanajo', 'brokenheart'),
    ('A tulip,', 'With no shadow,', 'Blossoms.', 'Hasegawa Kanajo', 'flower'),
    ('Japanese knotweed', 'Flowers had just given rise', 'A pastoral idyll.', 'Takahama Kyoshi', 'herb'),
    ('The canola flowers,', 'And the tide goes back', 'The small stream.', 'Masaoka Shiki', 'wave'),
    ('Someone dropped', 'Or dropped by itself on the street', 'The flower of camellia.', 'Masaoka Shiki', 'flower'),
    ('There is a wind,', 'The kerria bounces', 'The butterfly.', 'Masaoka Shiki', 'butterfly'),
    ('The dandelions', 'Are scattered on the green.', 'It''s spring field.', 'Masaoka Shiki', 'flower'),
    ('A tea flower,', 'The warmth days', 'Come to end.', 'Takahama Kyoshi', 'hibiscus'),
    ('Around the paper lantern', 'Fallen blossoms with the wind', 'Can be seen.', 'Takahama Kyoshi', 'lantern'),
    ('A tea flower,', 'The warmth days', 'Come to end.', 'Takahama Kyoshi', 'tea'),
    ('Burning fallen leaves,', 'The warm autumn day is', 'Defined.', 'Takahama Kyoshi', 'fall'),
    ('The distant mountain', 'Catch the sun.', 'The desolate field.', 'Takahama Kyoshi', 'sunset'),
    ('The clear day in the rainy season.', 'The madder red of the twilight appeared', 'And vanished instantly.', 'Takahama Kyoshi', 'sunset'),
    ('The short summer night.', 'The dream and real', 'Are same things.', 'Takahama Kyoshi', 'star'),
    ('The summer butterfly', 'Has a sharp look', 'And run to here.', 'Takahama Kyoshi', 'butterfly'),
    ('When the wind blows', 'The carp stream come', 'From the next door.', 'Takahama Kyoshi', 'fish'),
    ('In the bamboo grove', 'The yellow spring sunlight,', 'I look up at it.', 'Takahama Kyoshi', 'sun'),
    ('Saying something,', 'The lip feel cold.', 'The Autum wind.', 'Matsuo Basho', 'fall'),
    ('Ah, tranquility!', 'Penetrating the very rock, ', 'A cicada''s voice.', 'Matsuo Basho', 'mountain'),
    ('Grasses in summer.', 'The warriors'' dreams', 'All that left.', 'Matsuo Basho', 'herb'),
    ('The early summer rain', 'Leaves behind', 'Hikari-do.', 'Matsuo Basho', 'rain'),
    ('Spring is passing.', 'The birds cry, and the fishes fill', 'With tears on their eyes.', 'Matsuo Basho', 'rain'),
    ('Let''s go out', 'To see the snow view', 'Where we slip and fall.', 'Matsuo Basho', 'winter'),
    ('The snow and snow.', 'This evening would have', 'The great moon of December.', 'Matsuo Basho', 'moon'),
    ('In the dark night,', 'Losing sight of the nest,', 'The plover crys.', 'Matsuo Basho', 'stars'),
    ('Firstly, at the beginning of Spring,', 'They sell Sake and ume blossoms', 'And I smell them.', 'Matsuo Basho', 'sake'),
    ('It''s pleasant.', 'I''m cooled in the green paddy field.', 'And the sound of the water.', 'Matsuo Basho', 'herb'),
    ('Their own fire', 'Are on the trees, the fireflies', 'Around the house with flowers.', 'Matsuo Basho', 'fire'),
    ('In the autumn night, ', 'Breaking into', 'A pleasant chat.', 'Matsuo Basho', 'stars'),
    ('Holding the umbrella,', 'The mother is behind.', 'The autumn rain.', 'Nakamura Teijo', 'rain'),
    ('The autumn evening.', 'The buses are in line,', 'And one goes out.', 'Nakamura Teijo', 'bus'),
    ('The migratory birds', 'Make the wind blowing down to Asaka', 'From mountains frequently.', 'Kawahigashi Hekigoto', 'wind'),
    ('Oh, Matsuyama.', 'Higher than autumn,', 'The castle tower is.', 'Masaoka Shiki', 'tower'),
    ('In September', 'The sky wears', 'A lined kimono.', 'Kobayashi Issa', 'kimono'),
    ('The baby cow', 'Goes on a trip.', 'In the autumn rain.', 'Kobayashi Issa', 'cow'),
    ('A little boy sings', 'on a terrace, eyes aglow.', 'Ridge spills upward.', 'Robert Yehling', 'music'),
    ('meteor shower', 'a gentle wave', 'wets our sandals', 'Michael Dylan Welch', 'star'),
    ('Just friends: ', 'he watches my gauze dress', 'blowing on the line.', 'Alexis Rotella', 'dress'),
    ('Nightfall,', 'Too dark to read the page', 'Too cold.', 'Jack Kerouac', 'moon'),
    ('ground squirrel', 'balancing its tomato', 'on the garden fence', 'Don Eulert', 'tomato'),
    ('Lily:', 'out of the water', 'out of itself ', 'Nick Virgilio', 'flower'),
    ('From across the lake,', 'Past the black winter trees,', 'Faint sounds of a flute. ', 'Richard Wright', 'music'),
    ('The crow has flown away:', 'swaying in the evening sun,', 'a leafless tree.', 'Natsume Soseki', 'sunset'),
    ('Plum flower temple:', 'Voices rise', 'From the foothills', 'Natsume Soseki', 'hibiscus'),
    ('The lamp once out', 'Cool stars enter', 'The window frame.', 'Natsume Soseki', 'star'),
    ('A lightning flash:', 'between the forest trees', 'I have seen water.', 'Masaoka Shiki', 'tree'),
    ('The summer river:', 'although there is a bridge, my horse', 'goes through the water.', 'Masaoka Shiki', 'horse'),
    ('Night; and once again,', 'the while I wait for you, cold wind', 'turns into rain.', 'Masaoka Shiki', 'wind'),
    ('A mountain village', 'under the piled-up snow', 'the sound of water.', 'Masaoka Shiki', 'fuji'),
    ('For love and for hate', 'I swat a fly and offer it', 'to an ant.', 'Masaoka Shiki', 'gift'),
    ('After killing', 'a spider, how lonely I feel', 'in the cold of night!', 'Masaoka Shiki', 'web'),
    ('I want to sleep', 'Swat the flies', 'Softly, please.', 'Masaoka Shiki', 'sleep'),
    ('Everything I touch', 'with tenderness, alas,', 'pricks like a bramble.', 'Kobayashi Issa', 'herb'),
    ('Trusting the Buddha, good and bad,', 'I bid farewell', ' To the departing year.', 'Kobayashi Issa', 'party'),
    ('O snail', 'Climb Mount Fuji,', 'But slowly, slowly!', 'Kobayashi Issa', 'fuji'),
    ('In the moonlight,', 'The color and scent of the wisteria', 'Seems far away.', 'Yosa Buson', 'moon'),
    ('Light of the moon', 'Moves west, flowers'' shadows', 'Creep eastward.', 'Yosa Buson', 'moon'),
    ('A summer river being crossed', 'how pleasing', 'with sandals in my hands!', 'Yosa Buson', 'sandal'),
    ('In the twilight rain', 'these brilliant-hued hibiscus -', 'A lovely sunset.', 'Basho Matsuo', 'hibiscus'),
    ('Autumn moonlight—', 'a worm digs silently', 'into the chestnut.', 'Basho Matsuo', 'nut'),
    ('An old silent pond...', 'A frog jumps into the pond,', 'splash! Silence again.', 'Basho Matsuo', 'frog'),
    ('A white flower.', 'The spring is old days', 'And the dream is cold.', 'Ozaki Hosai', 'flower'),
    ('The spring rain,', 'I definitely saw', 'The fay of stone.', 'Murakami Kijo', 'rain'),
    ('The wild gooses', 'Got back wholly', 'And the moonless night.', 'Murakami Kijo', 'turkey'),
    ('The splash-splash,', 'The spring sea water dash against', 'The shrine torii gate.', 'Kawahigashi Hekigoto', 'wave'),
    ('Flutteringly,', 'Floating in the breeze,', 'A single butterfly.', 'Masaoka Shiki', 'butterfly'),
    ('I got drunk, a sleep.', 'And wept on the dream.', 'A wild cherry blossoms.', 'Masaoka Shiki', 'sun'),
    ('The spring breeze.', 'Being pulled by a cow', 'To the Zenkoji temple.', 'Kobayashi Issa', 'cow'),
    ('The fading of spring.', 'The feeling of holding', 'Of the biwa.', 'Yosa Buson', 'sun'),
    ('The spring rain.', 'Talking and passing', 'The straw rain‐cape and umbrella.', 'Yosa Buson', 'rain'),
    ('The baby spallows,', 'Make way, make way.', 'The horse is going to pass along.', 'Kobayashi Issa', 'babybird'),
    ('Thick blanket of snow', 'snuggling the flowerbeds', 'with a winter wrap', 'Jan Allison', 'winter'),
    ('Tiny snow angel', 'snowflakes kiss your rosy cheeks', 'white winter beauty', 'Jan Allison', 'winter'),
    ('Biting icy winds', 'thermal clothes protecting me', 'from the winter chill', 'Jan Allison', 'winter'),
    ('A long winter ends', 'Flowers prism the sunshine', 'Life begins anew', 'Allen Mersereaux', 'sun'),
    ('Quick change artist, Fall', 'dons her crimsons and yellows', 'as winter watches', 'Joyce Johnson', 'fall'),
    ('Ancient branches break', 'with weight of winter season', 'fresh born fawn stands straight', 'Tom Mcmurray', 'winter'),
    ('Cold Winter Night,', 'Mind''s Shivering with Thoughts, but', 'Ink''s Frozen.', 'Harshath Vidheya', 'winter'),
    ('Breeze teasing Palm trees,', 'Turtles sunning by the pond,', 'Lovely winter day.', 'Robert A. Dufresne', 'winter');


INSERT INTO emojis (name, code) VALUES
   
    ('cat', '1F408'),
    ('brokenheart', '1F494'),
    ('lantern', '1F3EE'),
    ('tea', '1F375'),
    ('fish', '1F41F'),
    ('mountain', '26F0'),
    ('sake', '1F376'),
    ('fire', '1F525'),
    ('stars', '1F30C'),
    ('tower', '1F5FC'),
    ('kimono', '1F458'),
    ('bus', '1F68D'),
    ('dress', '1F457'),
    ('tomato', '1F345'),
    ('music', '1F3B6'),
    ('sunset', '1F304'),
    ('star', '1F320'),
    ('tree', '1F333'),
    ('horse', '1F40E'),
    ('wind', '1F32C'),
    ('gift', '1F381'),
    ('web', '1F578'),
    ('sleep', '1F634'),
    ('herb', '1F33F'),
    ('party', '1F389'),
    ('fuji', '1F5FB'),
    ('moon', '1F315'),
    ('sandal', '1F461'),
    ('nut', '1F330'),
    ('frog', '1F438'),
    ('flower', 'blossom'),
    ('turkey', '1F983'),
    ('wave', '1F30A'),
    ('butterfly', '1F98B'),
    ('cow', '1F404'),
    ('turtle', '1F422'),
    ('sun', '2600'),
    ('fall', '1F342'),
    ('rain', '1F326'),
    ('babybird', '1F424'),
    ('hibiscus', '1F33A'),
    ('winter', '2744');

