INSERT INTO haikus (line1, line2, line3, author, emoji) VALUES

    ('A little boy sings', 'on a terrace, eyes aglow.', 'Ridge spills upward.', 'Robert Yehling', 'music'),
    ('meteor shower', 'a gentle wave', 'wets our sandals', 'Michael Dylan Welch', 'star'),
    ('Just friends: ', 'he watches my gauze dress', 'blowing on the line.', 'Alexis Rotella', 'dress'),
    ('Nightfall,', 'Too dark to read the page', 'Too cold.', 'Jack Kerouac', 'moon'),
    ('ground squirrel', 'balancing its tomato', 'on the garden fence', 'Don Eulert', 'tomato'),
    ('Lily:', 'out of the water', 'out of itself ', 'Nick Virgilio', 'flower'),
    ('From across the lake,', 'Past the black winter trees,', 'Faint sounds of a flute. ', 'Richard Wright', 'music'),
    ('The crow has flown away:', 'swaying in the evening sun,', 'a leafless tree.', 'Natsume Soseki', 'sunset'),
    ('Plum flower temple:', 'Voices rise', 'From the foothills', 'Natsume Soseki', 'hibiscus'),
    ('The lamp once out', 'Cool stars enter', 'The window frame.', 'Natsume Soseki', 'star'),
    ('A lightning flash:', 'between the forest trees', 'I have seen water.', 'Masaoka Shiki', 'tree'),
    ('The summer river:', 'although there is a bridge, my horse', 'goes through the water.', 'Masaoka Shiki', 'horse'),
    ('Night; and once again,', 'the while I wait for you, cold wind', 'turns into rain.', 'Masaoka Shiki', 'wind'),
    ('A mountain village', 'under the piled-up snow', 'the sound of water.', 'Masaoka Shiki', 'fuji'),
    ('For love and for hate', 'I swat a fly and offer it', 'to an ant.', 'Masaoka Shiki', 'gift'),
    ('After killing', 'a spider, how lonely I feel', 'in the cold of night!', 'Masaoka Shiki', 'web'),
    ('I want to sleep', 'Swat the flies', 'Softly, please.', 'Masaoka Shiki', 'sleep'),
    ('Everything I touch', 'with tenderness, alas,', 'pricks like a bramble.', 'Kobayashi Issa', 'herb'),
    ('Trusting the Buddha, good and bad,', 'I bid farewell', ' To the departing year.', 'Kobayashi Issa', 'party'),
    ('O snail', 'Climb Mount Fuji,', 'But slowly, slowly!', 'Kobayashi Issa', 'fuji'),
    ('In the moonlight,', 'The color and scent of the wisteria', 'Seems far away.', 'Yosa Buson', 'moon'),
    ('Light of the moon', 'Moves west, flowers'' shadows', 'Creep eastward.', 'Yosa Buson', 'moon'),
    ('A summer river being crossed', 'how pleasing', 'with sandals in my hands!', 'Yosa Buson', 'sandal'),
    ('In the twilight rain', 'these brilliant-hued hibiscus -', 'A lovely sunset.', 'Basho Matsuo', 'hibiscus'),
    ('Autumn moonlight—', 'a worm digs silently', 'into the chestnut.', 'Basho Matsuo', 'nut'),
    ('An old silent pond...', 'A frog jumps into the pond,', 'splash! Silence again.', 'Basho Matsuo', 'frog'),
    ('A white flower.', 'The spring is old days', 'And the dream is cold.', 'Ozaki Hosai', 'flower'),
    ('The spring rain,', 'I definitely saw', 'The fay of stone.', 'Murakami Kijo', 'rain'),
    ('The wild gooses', 'Got back wholly', 'And the moonless night.', 'Murakami Kijo', 'turkey'),
    ('The splash-splash,', 'The spring sea water dash against', 'The shrine torii gate.', 'Kawahigashi Hekigoto', 'wave'),
    ('Flutteringly,', 'Floating in the breeze,', 'A single butterfly.', 'Masaoka Shiki', 'butterfly'),
    ('I got drunk, a sleep.', 'And wept on the dream.', 'A wild cherry blossoms.', 'Masaoka Shiki', 'sun'),
    ('The spring breeze.', 'Being pulled by a cow', 'To the Zenkoji temple.', 'Kobayashi Issa', 'cow'),
    ('The fading of spring.', 'The feeling of holding', 'Of the biwa.', 'Yosa Buson', 'sun'),
    ('The spring rain.', 'Talking and passing', 'The straw rain‐cape and umbrella.', 'Yosa Buson', 'rain'),
    ('The baby spallows,', 'Make way, make way.', 'The horse is going to pass along.', 'Kobayashi Issa', 'babybird'),
    ('Thick blanket of snow', 'snuggling the flowerbeds', 'with a winter wrap', 'Jan Allison', 'winter'),
    ('Tiny snow angel', 'snowflakes kiss your rosy cheeks', 'white winter beauty', 'Jan Allison', 'winter'),
    ('Biting icy winds', 'thermal clothes protecting me', 'from the winter chill', 'Jan Allison', 'winter'),
    ('A long winter ends', 'Flowers prism the sunshine', 'Life begins anew', 'Allen Mersereaux', 'sun'),
    ('Quick change artist, Fall', 'dons her crimsons and yellows', 'as winter watches', 'Joyce Johnson', 'fall'),
    ('Ancient branches break', 'with weight of winter season', 'fresh born fawn stands straight', 'Tom Mcmurray', 'winter'),
    ('Cold Winter Night,', 'Mind''s Shivering with Thoughts, but', 'Ink''s Frozen.', 'Harshath Vidheya', 'winter'),
    ('Breeze teasing Palm trees,', 'Turtles sunning by the pond,', 'Lovely winter day.', 'Robert A. Dufresne', 'winter');



INSERT INTO emojis (name, code) VALUES
    
    ('dress', '1F457'),
    ('tomato', '1F345'),
    ('music', '1F3B6'),
    ('sunset', '1F304'),
    ('star', '1F320'),
    ('tree', '1F333'),
    ('horse', '1F40E'),
    ('wind', '1F32C'),
    ('gift', '1F381'),
    ('web', '1F578'),
    ('sleep', '1F634'),
    ('herb', '1F33F'),
    ('party', '1F389'),
    ('fuji', '1F5FB'),
    ('moon', '1F315'),
    ('sandal', '1F461'),
    ('nut', '1F330'),
    ('frog', '1F438'),
    ('flower', 'blossom'),
    ('turkey', '1F983'),
    ('wave', '1F30A'),
    ('butterfly', '1F98B'),
    ('cow', '1F404'),
    ('turtle', '1F422'),
    ('sun', '2600'),
    ('fall', '1F342'),
    ('rain', '1F326'),
    ('babybird', '1F424'),
    ('hibiscus', '1F33A'),
    ('winter', '2744');